DictConfig __getitem__ access, e.g. `cfg["foo"]`, is now raising a KeyError if the key "foo" does not exist
